# Generated by Django 3.1.4 on 2020-12-07 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user')),
                ('model', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
