# Generated by Django 3.1.8 on 2021-09-11 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweetgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkovChainState3',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state0', models.TextField(db_index=True)),
                ('state1', models.TextField(db_index=True)),
                ('state2', models.TextField(db_index=True)),
                ('next', models.TextField()),
                ('value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
