# Generated by Django 3.1.8 on 2021-05-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='twitter_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='Twitter id'),
        ),
    ]
