# Generated by Django 3.1.8 on 2022-01-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210526_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='screen_name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='screen name'),
        ),
    ]
